# fly.toml app configuration file generated for boilerplate-paid-mcp on 2025-06-26T17:33:57+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'boilerplate-paid-mcp'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
